# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import sys
import pandas as pd


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 650)
        self.b_filtercoffee = QtWidgets.QPushButton(Dialog)
        self.b_filtercoffee.setGeometry(QtCore.QRect(80, 140, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.b_filtercoffee.setFont(font)
        self.b_filtercoffee.setStyleSheet(
            "border-radius:16px;\n"
            "border-color: rgb(199, 98, 50);\n"
            "background-color:rgb(255, 211, 189);\n"
            "color:rgb(0, 0, 0)"
        )
        self.b_filtercoffee.setObjectName("b_filtercoffee")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 800, 650))
        self.widget.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.widget.setObjectName("widget")
        self.b_espresso = QtWidgets.QPushButton(self.widget)
        self.b_espresso.setGeometry(QtCore.QRect(80, 220, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.b_espresso.setFont(font)
        self.b_espresso.setStyleSheet(
            "border-radius:16px;\n"
            "border-color: rgb(199, 98, 50);\n"
            "background-color:rgb(255, 211, 189);\n"
            "color:rgb(0, 0, 0)\n"
            ""
        )
        self.b_espresso.setObjectName("b_espresso")
        self.b_americano = QtWidgets.QPushButton(self.widget)
        self.b_americano.setGeometry(QtCore.QRect(80, 300, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.b_americano.setFont(font)
        self.b_americano.setStyleSheet(
            "border-radius:16px;\n"
            "border-color: rgb(199, 98, 50);\n"
            "background-color:rgb(255, 211, 189);\n"
            "color:rgb(0, 0, 0)"
        )
        self.b_americano.setObjectName("b_americano")
        self.b_latte = QtWidgets.QPushButton(self.widget)
        self.b_latte.setGeometry(QtCore.QRect(80, 380, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.b_latte.setFont(font)
        self.b_latte.setStyleSheet(
            "border-radius:16px;\n"
            "border-color: rgb(199, 98, 50);\n"
            "background-color:rgb(255, 211, 189);\n"
            "color:rgb(0, 0, 0)"
        )
        self.b_latte.setObjectName("b_latte")
        self.b_amerc_plus = QtWidgets.QPushButton(self.widget)
        self.b_amerc_plus.setGeometry(QtCore.QRect(270, 300, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.b_amerc_plus.setFont(font)
        self.b_amerc_plus.setStyleSheet(
            "border-radius:16px;\n"
            "border-color: rgb(199, 98, 50);\n"
            "background-color: rgb(255, 255, 255);\n"
            "color:rgb(0, 0, 0)"
        )
        self.b_amerc_plus.setObjectName("b_amerc_plus")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(420, 570, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(0, 0, 0)")
        self.label.setObjectName("label")
        self.check = QtWidgets.QLabel(self.widget)
        self.check.setGeometry(QtCore.QRect(632, 590, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.check.setFont(font)
        self.check.setStyleSheet("color:rgb(0,0,0)\n" "")
        self.check.setObjectName("check")
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setGeometry(QtCore.QRect(360, 540, 233, 41))
        self.textEdit.setStyleSheet("color:rgb(0,0,0);\n" "border-color:rgb(0,0,0)")
        self.textEdit.setObjectName("textEdit")
        self.b_latte_plus = QtWidgets.QPushButton(self.widget)
        self.b_latte_plus.setGeometry(QtCore.QRect(270, 380, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.b_latte_plus.setFont(font)
        self.b_latte_plus.setStyleSheet(
            "border-radius:16px;\n"
            "border-color: rgb(199, 98, 50);\n"
            "background-color: rgb(255, 255, 255);\n"
            "color:rgb(0, 0, 0)"
        )
        self.b_latte_plus.setObjectName("b_latte_plus")
        self.b_esp_plus = QtWidgets.QPushButton(self.widget)
        self.b_esp_plus.setGeometry(QtCore.QRect(270, 220, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.b_esp_plus.setFont(font)
        self.b_esp_plus.setStyleSheet(
            "border-radius:16px;\n"
            "border-color: rgb(199, 98, 50);\n"
            "background-color: rgb(255, 255, 255);\n"
            "color:rgb(0, 0, 0)"
        )
        self.b_esp_plus.setObjectName("b_esp_plus")
        self.b_filter_plus = QtWidgets.QPushButton(self.widget)
        self.b_filter_plus.setGeometry(QtCore.QRect(270, 140, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.b_filter_plus.setFont(font)
        self.b_filter_plus.setStyleSheet(
            "border-radius:16px;\n"
            "border-color: rgb(199, 98, 50);\n"
            "background-color: rgb(255, 255, 255);\n"
            "color:rgb(0, 0, 0)"
        )
        self.b_filter_plus.setObjectName("b_filter_plus")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(389, 490, 151, 32))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet(
            "border-radius:16px;\n"
            "border-color: rgb(199, 98, 50);\n"
            "background-color: rgb(255, 255, 255);\n"
            "color:rgb(0, 0, 0)"
        )
        icon = QtGui.QIcon.fromTheme("backwardbend.png")
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 490, 151, 32))
        self.pushButton_2.setStyleSheet(
            "border-radius:16px;\n"
            "border-color: rgb(199, 98, 50);\n"
            "background-color: rgb(21, 115, 215);\n"
            "color:rgb(255,255,255)"
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.order_id_label = QtWidgets.QLabel(self.widget)
        self.order_id_label.setGeometry(QtCore.QRect(80, 50, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.order_id_label.setFont(font)
        self.order_id_label.setStyleSheet("color:rgb(255,255,255)")
        self.order_id_label.setObjectName("order_id_label")
        self.order_id = QtWidgets.QLabel(self.widget)
        self.order_id.setGeometry(QtCore.QRect(260, 50, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.order_id.setFont(font)
        self.order_id.setStyleSheet("color:rgb(255,255,255)")
        self.order_id.setObjectName("order_id")
        self.b_espresso.raise_()
        self.b_americano.raise_()
        self.b_latte.raise_()
        self.b_amerc_plus.raise_()
        self.label.raise_()
        self.check.raise_()
        self.textEdit.raise_()
        self.b_latte_plus.raise_()
        self.b_esp_plus.raise_()
        self.b_filter_plus.raise_()
        self.pushButton_2.raise_()
        self.pushButton.raise_()
        self.order_id_label.raise_()
        self.order_id.raise_()

        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(355, 111, 381, 364))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.rowCount = self.tableWidget.rowCount()
        self.widget.raise_()
        self.b_filtercoffee.raise_()
        self.tableWidget.raise_()

        # button connections
        self.b_filtercoffee.clicked.connect(self.clicked)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.b_filtercoffee.setText(_translate("Dialog", "Filter Coffee"))
        self.b_espresso.setText(_translate("Dialog", "Espresso"))
        self.b_americano.setText(_translate("Dialog", "Americano"))
        self.b_latte.setText(_translate("Dialog", "Latte"))
        self.b_amerc_plus.setText(_translate("Dialog", "+"))
        self.label.setText(_translate("Dialog", "Total:"))
        self.check.setText(_translate("Dialog", "0.00"))
        self.textEdit.setHtml(
            _translate(
                "Dialog",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'.AppleSystemUIFont'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'MS Shell Dlg 2\'; font-size:18pt;">COUPON CODE</span></p></body></html>',
            )
        )
        self.b_latte_plus.setText(_translate("Dialog", "+"))
        self.b_esp_plus.setText(_translate("Dialog", "+"))
        self.b_filter_plus.setText(_translate("Dialog", "+"))
        self.pushButton.setText(_translate("Dialog", "Cancel"))
        self.pushButton_2.setText(_translate("Dialog", "OK"))
        self.order_id_label.setText(_translate("Dialog", "ORDER"))
        self.order_id.setText(_translate("Dialog", "0001"))

    def clicked(self):
        print("hey")
        self.rowPosition = self.tableWidget.rowCount()
        self.tableWidget.insertRow(self.rowPosition)
        # self.tableWidget.setItem(self.rowPosition, 0, QTableWidgetItem("name"))
        self.last = self.tableWidget.rowCount()
        self.tableWidget.setItem(self.last, 0, QTableWidgetItem("text1"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
