# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/GoogleDrive/My Drive/Python/StockManager/view/deneme_anamenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.go_1 = QtWidgets.QPushButton(self.centralwidget)
        self.go_1.setObjectName("go_1")
        self.verticalLayout.addWidget(self.go_1)
        self.go_2 = QtWidgets.QPushButton(self.centralwidget)
        self.go_2.setObjectName("go_2")
        self.verticalLayout.addWidget(self.go_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.first_menu_b = QtWidgets.QPushButton(self.page)
        self.first_menu_b.setGeometry(QtCore.QRect(230, 150, 100, 32))
        self.first_menu_b.setObjectName("first_menu_b")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.second_menu_b = QtWidgets.QPushButton(self.page_2)
        self.second_menu_b.setGeometry(QtCore.QRect(160, 180, 100, 32))
        self.second_menu_b.setObjectName("second_menu_b")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.go_1.setText(_translate("MainWindow", "1"))
        self.go_2.setText(_translate("MainWindow", "2"))
        self.first_menu_b.setText(_translate("MainWindow", "1"))
        self.second_menu_b.setText(_translate("MainWindow", "2"))
