# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/GoogleDrive/My Drive/Python/StockManager/preferences.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tercihler_layout = QtWidgets.QVBoxLayout()
        self.tercihler_layout.setObjectName("tercihler_layout")
        self.gridLayout.addLayout(self.tercihler_layout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.iptal_button = QtWidgets.QPushButton(Dialog)
        self.iptal_button.setObjectName("iptal_button")
        self.horizontalLayout.addWidget(self.iptal_button)
        self.tamam_button = QtWidgets.QPushButton(Dialog)
        self.tamam_button.setObjectName("tamam_button")
        self.horizontalLayout.addWidget(self.tamam_button)
        self.onayla_button = QtWidgets.QPushButton(Dialog)
        self.onayla_button.setObjectName("onayla_button")
        self.horizontalLayout.addWidget(self.onayla_button)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.iptal_button.setText(_translate("Dialog", "Iptal"))
        self.tamam_button.setText(_translate("Dialog", "Tamam"))
        self.onayla_button.setText(_translate("Dialog", "Onayla"))
