# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)

        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")


        self.tercihler_layout = QtWidgets.QVBoxLayout()
        self.tercihler_layout.setObjectName("tercihler_layout")

        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.kupon_indirimi_check = QtWidgets.QCheckBox(Dialog)
        self.kupon_indirimi_check.setText("")
        self.kupon_indirimi_check.setObjectName("kupon_indirimi_check")
        self.horizontalLayout_8.addWidget(self.kupon_indirimi_check)

        
        self.tercihler_layout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.kategori_check = QtWidgets.QCheckBox(Dialog)
        self.kategori_check.setText("")
        self.kategori_check.setObjectName("kategori_check")
        self.horizontalLayout_9.addWidget(self.kategori_check)
        self.tercihler_layout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.checkBox_4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_5.addWidget(self.checkBox_4)
        self.tercihler_layout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.tercihler_layout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.iptal_button = QtWidgets.QPushButton(Dialog)
        self.iptal_button.setObjectName("iptal_button")
        self.horizontalLayout.addWidget(self.iptal_button)
        self.tamam_button = QtWidgets.QPushButton(Dialog)
        self.tamam_button.setObjectName("tamam_button")
        self.horizontalLayout.addWidget(self.tamam_button)
        self.onayla_button = QtWidgets.QPushButton(Dialog)
        self.onayla_button.setObjectName("onayla_button")
        self.horizontalLayout.addWidget(self.onayla_button)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "Kupon indirimi"))
        self.label_7.setText(_translate("Dialog", "Kategoriler"))
        self.label_8.setText(_translate("Dialog", "TextLabel"))
        self.iptal_button.setText(_translate("Dialog", "Iptal"))
        self.tamam_button.setText(_translate("Dialog", "Tamam"))
        self.onayla_button.setText(_translate("Dialog", "Onayla"))
