# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/GoogleDrive/My Drive/Python/StockManager/order_enter.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 600)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 400, 600))
        self.widget.setObjectName("widget")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 400, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.urun_sayisi = QtWidgets.QSpinBox(self.tab)
        self.urun_sayisi.setObjectName("urun_sayisi")
        self.horizontalLayout.addWidget(self.urun_sayisi)
        self.onay_button = QtWidgets.QPushButton(self.tab)
        self.onay_button.setObjectName("onay_button")
        self.horizontalLayout.addWidget(self.onay_button)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.urun_tablosu = QtWidgets.QTableWidget(self.tab)
        self.urun_tablosu.setObjectName("urun_tablosu")
        self.urun_tablosu.setColumnCount(2)
        self.urun_tablosu.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.urun_tablosu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.urun_tablosu.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.urun_tablosu, 0, 0, 1, 1)
        self.kategori_ekle_layout = QtWidgets.QHBoxLayout()
        self.kategori_ekle_layout.setObjectName("kategori_ekle_layout")
        self.kategori_ekle_edit = QtWidgets.QLineEdit(self.tab)
        self.kategori_ekle_edit.setObjectName("kategori_ekle_edit")
        self.kategori_ekle_layout.addWidget(self.kategori_ekle_edit)
        self.new_tab_button = QtWidgets.QPushButton(self.tab)
        self.new_tab_button.setObjectName("new_tab_button")
        self.kategori_ekle_layout.addWidget(self.new_tab_button)
        self.gridLayout.addLayout(self.kategori_ekle_layout, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.onay_button.setText(_translate("Dialog", "Onayla"))
        item = self.urun_tablosu.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Urun"))
        item = self.urun_tablosu.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Fiyat"))
        self.new_tab_button.setText(_translate("Dialog", "Kategori Ekle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Tab 2"))
